### ISSUE TITLE
Not authenticated

### ISSUE THREAD

**Issue by CharricosBack** [FacturAPI/facturapi-php#29]
Buenas tardes, solicito ayuda sobre el siguiente error:

```
[2024-06-10 14:39:02] local.DEBUG: Unable to create Invoice: Facturapi\Exceptions\Facturapi_Exception: Not authenticated in /var/www/html/liceth/vendor/facturapi/facturapi-php/src/Http/BaseClient.php:208
Stack trace:
#0 /var/www/html/liceth/vendor/facturapi/facturapi-php/src/Resources/Invoices.php(58): Facturapi\Http\BaseClient->execute_JSON_post_request()
#1 /var/www/html/liceth/app/Libraries/BillLibrary.php(247): Facturapi\Resources\Invoices->create()
#2 /var/www/html/liceth/app/Http/Controllers/BillController.php(97): App\Libraries\BillLibrary->createBill()
#3 /var/www/html/liceth/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\BillController->createBill()
...
```
 

Ya se verifico el payload que se genera para la creacion del Invoice, que apunta a:

```

 $invoice = $facturapi->Invoices->create([
                "customer" => [
                    "legal_name" => $request->name,
                    "email" => $request->email,
                    "tax_id" => $request->rfc,
                    "tax_system" => $request->regime,                      // Régimen Fiscal en el documento
                    "address" => [
                        "zip" => $request->zip
                    ]
                ],
                "use" => $request->use,                                  // Uso CFDI en el documento
                "payment_method" => "PUE",                               // PPD Pago en parcialidades
                "items" => $product,
                "payment_form" => $request->typepayment,                 //  Forma de pago en el documento
                //"folio_number" => 581,
                //"series" => "F"
            ]);

```

            
            Linea $product. Sin embargo ya se hizo pruebas en playground y retorna sin detalles la factura de prueba, en produccion cambia el detalle y retorna no atuhenticated.

**Comment by javorosas** [comment]
Gracias por el reporte.

Por el stacktrace (Facturapi_Exception y execute_JSON_post_request) esto corresponde a una versión anterior del SDK. Recomendamos actualizar primero a la versión más reciente de facturapi/facturapi-php.

Sobre Not authenticated: en estos casos casi siempre es configuración de credenciales en el entorno de producción, no el payload de la factura. Vale la pena revisar:

API key correcta en producción (sin espacios extra).
No mezclar key de test/live.
Que la variable de entorno que usa la app sea la que esperas.

Si después de actualizar sigue ocurriendo, te pido que le compartas tu Log ID al equipo de soporte.
